USE [master]
GO

CREATE DATABASE [ds]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ds', FILENAME = N'/var/opt/mssql/data/ds.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ds_log', FILENAME = N'/var/opt/mssql/data/ds_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ds].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ds] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ds] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ds] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ds] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ds] SET ARITHABORT OFF 
GO

ALTER DATABASE [ds] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ds] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ds] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ds] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ds] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ds] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ds] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ds] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ds] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ds] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ds] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ds] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ds] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ds] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ds] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ds] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ds] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ds] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ds] SET  MULTI_USER 
GO

ALTER DATABASE [ds] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ds] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ds] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ds] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ds] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ds] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ds] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ds] SET  READ_WRITE 
GO


